services:
  kattila-api:
    build: .
    container_name: kattila-api
    ports:
      - "5100:5100"
    develop:
      watch:
        - action: rebuild
          path: .
    secrets:
      - apikey
  redis:
    image: redis

secrets:
  apikey:
    file: "apikey.txt"
