name: Tests

on:
    - push
    - pull_request

permissions:
    contents: read

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout commit
              uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.x'
            - name: Install dependencies
              run: |
                python -m pip install --upgrade uv
                uv pip install --system --upgrade pip setuptools wheel
                uv pip install --system -r requirements-test.txt
            - name: Add testing API key
              run: echo TESTING_API_KEY > apikey.txt
            - name: Test with unittest
              env:
                API_KEY_FILE: apikey.txt
              run: python -m unittest
